### PR TITLE
Filter applied to a wrong view

### PR DESCRIPTION
**Pull request by kohsuke**
This filter was supposed to go to the pull request view, not branch view

@reviewbybees in particular @recena

### CODE REVIEW

**Comment by ghost** [comment]
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

**Comment by amuniz** [comment]
:bee:

**Comment by recena** [comment]
:bee:

**Comment by recena** [comment]
@reviewbybees done

**Pull request merged**
