### PR TITLE
[JENKINS-33797] Avoid an ugly exception in logs

### PR DESCRIPTION
**Pull request by amuniz**
[JENKINS-33797](https://issues.jenkins-ci.org/browse/JENKINS-33797)

@reviewbybees

### CODE REVIEW

**Comment by ghost** [comment]
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

**Comment by recena** [comment]
:bee: but the behavior described in the Jira issue can be improved including better support in the form validation.

**Comment by jglick** [comment]
:bee:

**Comment by recena** [comment]
@reviewbybees done

**Pull request merged**
