### PR TITLE
[JENKINS-39031] Switch to github-branch-source's ViewBranchFilter implememtations

### PR DESCRIPTION
**Pull request by stephenc**
@reviewbybees

See [JENKINS-39031](https://issues.jenkins-ci.org/browse/JENKINS-39031) downstream of https://github.com/jenkinsci/github-branch-source-plugin/pull/84

### CODE REVIEW

**Comment by ghost** [comment]
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

**Comment by rsandell** [comment]
:bee:

**Comment by stephenc** [comment]
@reviewbybees done

**Comment by ghost** [comment]
This pull request has completed our internal processes and we now respectfully request the maintainers of this repository to consider our proposal contained within this pull request for merging.

**Pull request merged**
