### PR TITLE
[JENKINS-39062] Move the GitHubRepositoryDescription column to github branch source

### PR DESCRIPTION
**Pull request by stephenc**
See [JENKINS-39062](https://issues.jenkins-ci.org/browse/JENKINS-39062)

@reviewbybees

### CODE REVIEW

**Comment by stephenc** [comment]
Downstream of https://github.com/jenkinsci/github-branch-source-plugin/pull/85

**Comment by ghost** [comment]
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

**Comment by rsandell** [comment]
:bee:

**Comment by stephenc** [comment]
@reviewbybees done

**Pull request merged**
