### PR TITLE
Upgraded main dependencies involved

### PR DESCRIPTION
**Pull request by recena**
I thought it would be interesing to upgrade the main dependencies to get the latest features and fixes since this plugin provides all you need to work with Pipelines and GitHub.

@reviewbybees especially @kohsuke

### CODE REVIEW

**Comment by ghost** [comment]
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

**Comment by kohsuke** [comment]
:bee:

**Comment by kzantow** [comment]
🐝

**Comment by recena** [comment]
Thank @kzantow @kohsuke

**Comment by daniel-beck** [comment]
What does this accomplish? If no new features are used, I don't really see an upside to this.

OTOH, I expect this may result in more upgrade installs of 2.0 not getting the restart-free experience, as it's more likely to have outdated dependencies installed.

**Comment by recena** [comment]
@daniel-beck There are users using this plugin in order to get a full experience about Pipeline and GitHub. For that reason, I think it is important to maintain updated its dependencies.

**Pull request merged**
