### PR TITLE
[JENKINS-33480] NPE

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-33480](https://issues.jenkins-ci.org/browse/JENKINS-33480)

as well as some buglets.

@reviewbybees esp. @kohsuke

### CODE REVIEW

**Comment by kohsuke** [comment]
:bee: 

Perhaps this plugin doing this much manipulation from a synchronous listener is just a bad idea. Maybe we should use some asynchronous execution with some delay. That way, rapid fire invocations of various listeners can be bundled up into one, too.

**Comment by ghost** [comment]
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

**Comment by oleg-nenashev** [comment]
:bee: I would rather prevent null return value in github-api, but it works for me as well

**Comment by jglick** [comment]
> I would rather prevent null return value in github-api

This NPE had nothing to do with `github-api`. Rather a case of some code running inside a constructor and passing around the half-constructed instance. Ultimately the fault of [this call](https://github.com/jenkinsci/cloudbees-folder-plugin/blob/8fdb613edd24cba6f446254e1323ca585ecbb336/src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolder.java#L236) which could perhaps be deleted, though that makes me a little nervous right now.

**Comment by jglick** [comment]
The synchronous listener is one contributing factor, though asynchronous listeners introduce their own problems too, testability in particular.

I suspect that removing the extra `save()` call would suffice to make things cleaner. One of the problems I saw was that the listener from this plugin was firing right after the mostly-unconfigured `OrganizationFolder` was created, which among other things would try to contact GitHub with anonymous credentials, typically failing with a rate limit error.

**Pull request merged**
